services:
  lightrag:
    build: .
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage:z
      - ./data/inputs:/app/data/inputs:z
      - ./config.ini:/app/config.ini:z
      - ./.env:/app/.env:z
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  neo4j:
    image: neo4j:5.26.4-community
    container_name: lightrag-server_neo4j-community
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_bolt_advertised__address=neo4j:7687
    volumes:
      - ./neo4j/plugins:/var/lib/neo4j/plugins:z
      - lightrag_neo4j_import:/var/lib/neo4j/import:z
      - lightrag_neo4j_data:/data:z
      - lightrag_neo4j_backups:/backups:z
    extra_hosts:
      - "host.docker.internal:host-gateway"


  # busybox:
  #   image: busybox
  #   container_name: lightrag-server_busybox
  #   restart: always
  #   volumes:
  #     - ./data/rag_storage:/app/data/rag_storage:z
  #     - ./data/inputs:/app/data/inputs:z
  #   entrypoint: /bin/sh -c "tail -f /dev/null"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  # postgres_client:
  #   image: pgclient:latest
  #   container_name: lightrag_postgres_client
  #   restart: always
  #   depends_on:
  #     postgres: 
  #       condition: service_started

  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
  #     POSTGRES_DB: ${POSTGRES_DB-postgres}
  #   # multiline entrypoint to wait for postgres to be ready
  #   # and create the vector extension
  #   entrypoint: sh -c 'until pg_isready -h postgres -p 5432; do sleep 1; done; echo "POSTGRES SQL IS READY!!!!!!!!!!!!!!!!!" && psql postgres://postgres:postgres@postgres:5432/postgres -c "CREATE EXTENSION IF NOT EXISTS vector;"'
  # postgres:
  #   image: postgres-vector:latest
  #   container_name: lightrag_postgres
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - .env

  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
  #     POSTGRES_DB: ${POSTGRES_DB-postgres}
  #   volumes:
  #     - ./data/lightrag_postgres_data:/var/lib/postgresql/data:z
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

volumes:
  lightrag_neo4j_import:
  lightrag_neo4j_data:
  lightrag_neo4j_backups:
  lightrag_postgres_data:
